# ============================================================
# TH06 Shader Embedding
#
# Input:
#   INPUT_VERT = ff.vert
#   INPUT_FRAG = ff.frag
#
# Output:
#   Embeds.hpp
#
# Generated arrays:
#   vertShaderBytes[]
#   fragShaderBytes[]
# ============================================================

cmake_minimum_required(VERSION 3.24)


# ============================================================
# Check arguments
# ============================================================

if(NOT DEFINED INPUT_VERT)
    message(FATAL_ERROR
        "INPUT_VERT is not defined"
    )
endif()

if(NOT DEFINED INPUT_FRAG)
    message(FATAL_ERROR
        "INPUT_FRAG is not defined"
    )
endif()

if(NOT DEFINED OUTPUT)
    message(FATAL_ERROR
        "OUTPUT is not defined"
    )
endif()


# ============================================================
# Check input files
# ============================================================

if(NOT EXISTS "${INPUT_VERT}")
    message(FATAL_ERROR
        "Vertex shader not found:\n${INPUT_VERT}"
    )
endif()

if(NOT EXISTS "${INPUT_FRAG}")
    message(FATAL_ERROR
        "Fragment shader not found:\n${INPUT_FRAG}"
    )
endif()


# ============================================================
# Read shader files as HEX
# ============================================================

file(
    READ
    "${INPUT_VERT}"
    VERT_HEX
    HEX
)

file(
    READ
    "${INPUT_FRAG}"
    FRAG_HEX
    HEX
)


# ============================================================
# Get HEX lengths
# ============================================================

string(
    LENGTH
    "${VERT_HEX}"
    VERT_LEN
)

string(
    LENGTH
    "${FRAG_HEX}"
    FRAG_LEN
)


# ============================================================
# Make output directory
# ============================================================

get_filename_component(
    OUTPUT_DIR
    "${OUTPUT}"
    DIRECTORY
)

if(NOT EXISTS "${OUTPUT_DIR}")
    file(
        MAKE_DIRECTORY
        "${OUTPUT_DIR}"
    )
endif()


# ============================================================
# Start generated header
# ============================================================

file(
    WRITE
    "${OUTPUT}"
    "#pragma once\n\n"
)

file(
    APPEND
    "${OUTPUT}"
    "// ============================================================\n"
)

file(
    APPEND
    "${OUTPUT}"
    "// TH06 Embedded Shaders\n"
)

file(
    APPEND
    "${OUTPUT}"
    "// This file is automatically generated.\n"
)

file(
    APPEND
    "${OUTPUT}"
    "// Do not edit manually.\n"
)

file(
    APPEND
    "${OUTPUT}"
    "// ============================================================\n\n"
)


# ============================================================
# Vertex shader
# ============================================================

file(
    APPEND
    "${OUTPUT}"
    "// ============================================================\n"
)

file(
    APPEND
    "${OUTPUT}"
    "// Vertex shader\n"
)

file(
    APPEND
    "${OUTPUT}"
    "// ============================================================\n\n"
)

file(
    APPEND
    "${OUTPUT}"
    "static const char vertShaderBytes[] = {\n"
)


if(VERT_LEN GREATER 0)

    # HEX string contains 2 characters per byte
    math(
        EXPR
        VERT_LAST="${VERT_LEN} - 2"
    )

    foreach(
        i
        RANGE
        0
        ${VERT_LAST}
        2
    )

        string(
            SUBSTRING
            "${VERT_HEX}"
            ${i}
            2
            BYTE
        )

        file(
            APPEND
            "${OUTPUT}"
            "0x${BYTE}, "
        )

    endforeach()

endif()


# Null terminator
file(
    APPEND
    "${OUTPUT}"
    "0x00\n};\n\n"
)


# ============================================================
# Fragment shader
# ============================================================

file(
    APPEND
    "${OUTPUT}"
    "// ============================================================\n"
)

file(
    APPEND
    "${OUTPUT}"
    "// Fragment shader\n"
)

file(
    APPEND
    "${OUTPUT}"
    "// ============================================================\n\n"
)

file(
    APPEND
    "${OUTPUT}"
    "static const char fragShaderBytes[] = {\n"
)


if(FRAG_LEN GREATER 0)

    # HEX string contains 2 characters per byte
    math(
        EXPR
        FRAG_LAST="${FRAG_LEN} - 2"
    )

    foreach(
        i
        RANGE
        0
        ${FRAG_LAST}
        2
    )

        string(
            SUBSTRING
            "${FRAG_HEX}"
            ${i}
            2
            BYTE
        )

        file(
            APPEND
            "${OUTPUT}"
            "0x${BYTE}, "
        )

    endforeach()

endif()


# Null terminator
file(
    APPEND
    "${OUTPUT}"
    "0x00\n};\n\n"
)


# ============================================================
# Final information
# ============================================================

file(
    APPEND
    "${OUTPUT}"
    "// ============================================================\n"
)

file(
    APPEND
    "${OUTPUT}"
    "// End of generated file\n"
)

file(
    APPEND
    "${OUTPUT}"
    "// ============================================================\n"
)


message(STATUS "========================================")
message(STATUS "TH06 Shader Embedding")
message(STATUS "========================================")
message(STATUS "Vertex shader:")
message(STATUS "  ${INPUT_VERT}")
message(STATUS "  ${VERT_LEN} HEX characters")
message(STATUS "  ${VERT_LEN} / 2 bytes")
message(STATUS "")
message(STATUS "Fragment shader:")
message(STATUS "  ${INPUT_FRAG}")
message(STATUS "  ${FRAG_LEN} HEX characters")
message(STATUS "  ${FRAG_LEN} / 2 bytes")
message(STATUS "")
message(STATUS "Output:")
message(STATUS "  ${OUTPUT}")
message(STATUS "========================================")
